import type {
  Dispatcher,
  GarageEvent,
  Job,
  Request,
  Vehicle,
} from './garage.types.js';

export const INITIAL_FLEET: Vehicle[] = [
  {
    id: '01',
    name: 'JCB 3CX',
    category: 'Экскаватор-погрузчик',
    plate: 'А 123 АА · 15',
    driver: 'Алексей Соколов',
    initials: 'АС',
    status: 'working',
    fuel: 76,
    hours: 2840,
    capacity: 'Ковш 1,0 м³',
  },
  {
    id: '02',
    name: 'SANY SY215C',
    category: 'Экскаватор',
    plate: 'В 456 ВВ · 15',
    driver: 'Дмитрий Козлов',
    initials: 'ДК',
    status: 'working',
    fuel: 62,
    hours: 1630,
    capacity: 'Ковш 1,1 м³',
  },
  {
    id: '03',
    name: 'КАМАЗ 65115',
    category: 'Самосвал',
    plate: 'М 789 ММ · 15',
    driver: 'Игорь Волков',
    initials: 'ИВ',
    status: 'working',
    fuel: 88,
    hours: 4320,
    capacity: 'Грузоподъёмность 15 т',
  },
  {
    id: '04',
    name: 'Галичанин КС-55713',
    category: 'Автокран',
    plate: 'К 215 КК · 15',
    driver: 'Олег Морозов',
    initials: 'ОМ',
    status: 'reserved',
    fuel: 92,
    hours: 2180,
    capacity: 'Грузоподъёмность 25 т',
  },
  {
    id: '05',
    name: 'Bobcat S530',
    category: 'Мини-погрузчик',
    plate: 'Е 032 ЕЕ · 15',
    driver: 'Павел Орлов',
    initials: 'ПО',
    status: 'ready',
    fuel: 95,
    hours: 970,
    capacity: 'Грузоподъёмность 869 кг',
  },
  {
    id: '06',
    name: 'Shantui SD16',
    category: 'Бульдозер',
    plate: 'Т 416 ТТ · 15',
    driver: 'Виктор Белов',
    initials: 'ВБ',
    status: 'service',
    fuel: 44,
    hours: 3500,
    capacity: 'Отвал 3,4 м³',
  },
  {
    id: '07',
    name: 'MAN TGS',
    category: 'Самосвал',
    plate: 'Н 518 НН · 15',
    driver: 'Андрей Петров',
    initials: 'АП',
    status: 'working',
    fuel: 68,
    hours: 3160,
    capacity: 'Грузоподъёмность 20 т',
  },
  {
    id: '08',
    name: 'Volvo EC220',
    category: 'Экскаватор',
    plate: 'С 728 СС · 15',
    driver: 'Сергей Романов',
    initials: 'СР',
    status: 'working',
    fuel: 71,
    hours: 2410,
    capacity: 'Ковш 1,2 м³',
  },
  {
    id: '09',
    name: 'XCMG GR180',
    category: 'Автогрейдер',
    plate: 'Р 604 РР · 15',
    driver: 'Роман Лебедев',
    initials: 'РЛ',
    status: 'working',
    fuel: 56,
    hours: 1950,
    capacity: 'Отвал 3,7 м',
  },
  {
    id: '10',
    name: 'JCB 4CX',
    category: 'Экскаватор-погрузчик',
    plate: 'Х 102 ХХ · 15',
    driver: 'Максим Егоров',
    initials: 'МЕ',
    status: 'ready',
    fuel: 100,
    hours: 840,
    capacity: 'Ковш 1,3 м³',
  },
  {
    id: '11',
    name: 'Амкодор 342В',
    category: 'Погрузчик',
    plate: 'О 311 ОО · 15',
    driver: 'Антон Фролов',
    initials: 'АФ',
    status: 'ready',
    fuel: 90,
    hours: 1720,
    capacity: 'Ковш 2,3 м³',
  },
  {
    id: '12',
    name: 'HAMM 3412',
    category: 'Каток',
    plate: 'У 912 УУ · 15',
    driver: 'Николай Зайцев',
    initials: 'НЗ',
    status: 'service',
    fuel: 57,
    hours: 2000,
    capacity: 'Рабочая масса 12 т',
  },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 1041,
    vehicle: '01',
    title: 'ЖК «Горизонт»',
    location: 'Разработка грунта',
    start: 8,
    end: 13,
    tone: 'lime',
  },
  {
    id: 1042,
    vehicle: '02',
    title: 'Промышленный парк',
    location: 'Рытьё котлована',
    start: 9,
    end: 17,
    tone: 'blue',
  },
  {
    id: 1043,
    vehicle: '03',
    title: 'Доставка щебня',
    location: 'Объездная дорога, участок 4',
    start: 8.5,
    end: 12,
    tone: 'lime',
  },
  {
    id: 1044,
    vehicle: '04',
    title: 'Монтаж перекрытий',
    location: 'ЖК «Южный»',
    start: 13,
    end: 18,
    tone: 'reserved',
  },
  {
    id: 1045,
    vehicle: '07',
    title: 'Вывоз грунта',
    location: 'ЖК «Горизонт»',
    start: 8,
    end: 16,
    tone: 'lime',
  },
  {
    id: 1046,
    vehicle: '08',
    title: 'Траншея водопровода',
    location: 'Промышленный парк',
    start: 9,
    end: 17,
    tone: 'blue',
  },
  {
    id: 1047,
    vehicle: '09',
    title: 'Профилирование дороги',
    location: 'Объездная дорога, участок 4',
    start: 8,
    end: 18,
    tone: 'lime',
  },
];

export const INITIAL_REQUESTS: Request[] = [
  {
    id: 1048,
    title: 'Планировка участка',
    location: 'ЖК «Северный», корпус 2',
    category: 'Экскаватор-погрузчик',
    start: 13,
    end: 17,
    urgent: true,
  },
  {
    id: 1049,
    title: 'Погрузка щебня',
    location: 'База «Стройресурс»',
    category: 'Погрузчик',
    start: 12,
    end: 15,
    urgent: false,
  },
  {
    id: 1050,
    title: 'Благоустройство',
    location: 'Сквер на Молодёжной',
    category: 'Мини-погрузчик',
    start: 14,
    end: 18,
    urgent: false,
  },
];

export const INITIAL_EVENTS: GarageEvent[] = [
  {
    time: '10:42',
    title: 'КАМАЗ 65115 прибыл на объект',
    detail: 'Игорь Волков · доставка щебня',
    type: 'arrival',
  },
  {
    time: '10:30',
    title: 'Новая срочная заявка № 1048',
    detail: 'ЖК «Северный» · требуется назначение',
    type: 'request',
  },
  {
    time: '10:15',
    title: 'Bobcat S530 готов к выезду',
    detail: 'Предсменный осмотр завершён',
    type: 'ready',
  },
];

export const DISPATCHERS: Dispatcher[] = [
  {
    name: 'Анна Миронова',
    initials: 'АМ',
    role: 'Старший диспетчер',
    time: '08:00–20:00',
    color: 'violet',
  },
  {
    name: 'Марк Дроздов',
    initials: 'МД',
    role: 'Диспетчер',
    time: '08:00–20:00',
    color: 'peach',
  },
  {
    name: 'Елена Новикова',
    initials: 'ЕН',
    role: 'Диспетчер',
    time: '10:00–22:00',
    color: 'mint',
  },
];
