import type {
  Branch,
  Dispatcher,
  Driver,
  Fueling,
  GarageEvent,
  Job,
  Request,
  StaffUser,
  TimesheetEntry,
  Vehicle,
  Waybill,
} from './garage.types.js';

export const DEMO_BRANCH: Branch = {
  id: 'b1',
  name: 'Основной филиал',
};

export const DEMO_STAFF: StaffUser[] = [
  {
    id: 'u-dispatcher',
    name: 'Анна Миронова',
    initials: 'АМ',
    role: 'dispatcher',
    branchId: 'b1',
  },
  {
    id: 'u-chief',
    name: 'Ирина Савельева',
    initials: 'ИС',
    role: 'branch_chief',
    branchId: 'b1',
  },
  {
    id: 'u-dept',
    name: 'Пётр Кузнецов',
    initials: 'ПК',
    role: 'department_head',
    branchId: 'b1',
  },
  {
    id: 'u-deputy',
    name: 'Ольга Сидорова',
    initials: 'ОС',
    role: 'deputy',
    branchId: 'b1',
  },
  {
    id: 'u-mechanic',
    name: 'Валерий Громов',
    initials: 'ВГ',
    role: 'mechanic',
    branchId: 'b1',
  },
  {
    id: 'u-master',
    name: 'Денис Крылов',
    initials: 'ДК',
    role: 'master',
    branchId: 'b1',
  },
];

export const INITIAL_DRIVERS: Driver[] = [
  { id: 'd01', fullName: 'Алексей Соколов', initials: 'АС', licenseCategory: 'C, E' },
  { id: 'd02', fullName: 'Дмитрий Козлов', initials: 'ДК', licenseCategory: 'C' },
  { id: 'd03', fullName: 'Игорь Волков', initials: 'ИВ', licenseCategory: 'C, E' },
  { id: 'd04', fullName: 'Олег Морозов', initials: 'ОМ', licenseCategory: 'C' },
  { id: 'd05', fullName: 'Павел Орлов', initials: 'ПО', licenseCategory: 'B, C' },
  { id: 'd06', fullName: 'Виктор Белов', initials: 'ВБ', licenseCategory: 'C' },
  { id: 'd07', fullName: 'Андрей Петров', initials: 'АП', licenseCategory: 'C, E' },
  { id: 'd08', fullName: 'Сергей Романов', initials: 'СР', licenseCategory: 'C' },
  { id: 'd09', fullName: 'Роман Лебедев', initials: 'РЛ', licenseCategory: 'C' },
  { id: 'd10', fullName: 'Максим Егоров', initials: 'МЕ', licenseCategory: 'B, C' },
  { id: 'd11', fullName: 'Антон Фролов', initials: 'АФ', licenseCategory: 'C' },
  { id: 'd12', fullName: 'Николай Зайцев', initials: 'НЗ', licenseCategory: 'C' },
  { id: 'd13', fullName: 'Кирилл Малов', initials: 'КМ', licenseCategory: 'C, E' },
];

export const INITIAL_FLEET: Vehicle[] = [
  {
    id: '01',
    name: 'JCB 3CX',
    category: 'Экскаватор-погрузчик',
    plate: 'А 123 АА · 15',
    driver: 'Алексей Соколов',
    initials: 'АС',
    driverId: 'd01',
    branchId: 'b1',
    status: 'working',
    fuel: 76,
    hours: 2840,
    capacity: 'Ковш 1,0 м³',
  },
  {
    id: '02',
    name: 'SANY SY215C',
    category: 'Экскаватор',
    plate: 'В 456 ВВ · 15',
    driver: 'Дмитрий Козлов',
    initials: 'ДК',
    driverId: 'd02',
    branchId: 'b1',
    status: 'working',
    fuel: 62,
    hours: 1630,
    capacity: 'Ковш 1,1 м³',
  },
  {
    id: '03',
    name: 'КАМАЗ 65115',
    category: 'Самосвал',
    plate: 'М 789 ММ · 15',
    driver: 'Игорь Волков',
    initials: 'ИВ',
    driverId: 'd03',
    branchId: 'b1',
    status: 'working',
    fuel: 88,
    hours: 4320,
    capacity: 'Грузоподъёмность 15 т',
  },
  {
    id: '04',
    name: 'Галичанин КС-55713',
    category: 'Автокран',
    plate: 'К 215 КК · 15',
    driver: 'Олег Морозов',
    initials: 'ОМ',
    driverId: 'd04',
    branchId: 'b1',
    status: 'reserved',
    fuel: 92,
    hours: 2180,
    capacity: 'Грузоподъёмность 25 т',
  },
  {
    id: '05',
    name: 'Bobcat S530',
    category: 'Мини-погрузчик',
    plate: 'Е 032 ЕЕ · 15',
    driver: 'Павел Орлов',
    initials: 'ПО',
    driverId: 'd05',
    branchId: 'b1',
    status: 'ready',
    fuel: 95,
    hours: 970,
    capacity: 'Грузоподъёмность 869 кг',
  },
  {
    id: '06',
    name: 'Shantui SD16',
    category: 'Бульдозер',
    plate: 'Т 416 ТТ · 15',
    driver: 'Виктор Белов',
    initials: 'ВБ',
    driverId: 'd06',
    branchId: 'b1',
    status: 'service',
    fuel: 44,
    hours: 3500,
    capacity: 'Отвал 3,4 м³',
  },
  {
    id: '07',
    name: 'MAN TGS',
    category: 'Самосвал',
    plate: 'Н 518 НН · 15',
    driver: 'Андрей Петров',
    initials: 'АП',
    driverId: 'd07',
    branchId: 'b1',
    status: 'working',
    fuel: 68,
    hours: 3160,
    capacity: 'Грузоподъёмность 20 т',
  },
  {
    id: '08',
    name: 'Volvo EC220',
    category: 'Экскаватор',
    plate: 'С 728 СС · 15',
    driver: 'Сергей Романов',
    initials: 'СР',
    driverId: 'd08',
    branchId: 'b1',
    status: 'working',
    fuel: 71,
    hours: 2410,
    capacity: 'Ковш 1,2 м³',
  },
  {
    id: '09',
    name: 'XCMG GR180',
    category: 'Автогрейдер',
    plate: 'Р 604 РР · 15',
    driver: 'Роман Лебедев',
    initials: 'РЛ',
    driverId: 'd09',
    branchId: 'b1',
    status: 'working',
    fuel: 56,
    hours: 1950,
    capacity: 'Отвал 3,7 м',
  },
  {
    id: '10',
    name: 'JCB 4CX',
    category: 'Экскаватор-погрузчик',
    plate: 'Х 102 ХХ · 15',
    driver: 'Максим Егоров',
    initials: 'МЕ',
    driverId: 'd10',
    branchId: 'b1',
    status: 'ready',
    fuel: 100,
    hours: 840,
    capacity: 'Ковш 1,3 м³',
  },
  {
    id: '11',
    name: 'Амкодор 342В',
    category: 'Погрузчик',
    plate: 'О 311 ОО · 15',
    driver: 'Антон Фролов',
    initials: 'АФ',
    driverId: 'd11',
    branchId: 'b1',
    status: 'ready',
    fuel: 90,
    hours: 1720,
    capacity: 'Ковш 2,3 м³',
  },
  {
    id: '12',
    name: 'HAMM 3412',
    category: 'Каток',
    plate: 'У 912 УУ · 15',
    driver: 'Николай Зайцев',
    initials: 'НЗ',
    driverId: 'd12',
    branchId: 'b1',
    status: 'service',
    fuel: 57,
    hours: 2000,
    capacity: 'Рабочая масса 12 т',
  },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 1041,
    vehicle: '01',
    title: 'ЖК «Горизонт»',
    location: 'Разработка грунта',
    start: 8,
    end: 13,
    tone: 'lime',
  },
  {
    id: 1042,
    vehicle: '02',
    title: 'Промышленный парк',
    location: 'Рытьё котлована',
    start: 9,
    end: 17,
    tone: 'blue',
  },
  {
    id: 1043,
    vehicle: '03',
    title: 'Доставка щебня',
    location: 'Объездная дорога, участок 4',
    start: 8.5,
    end: 12,
    tone: 'lime',
  },
  {
    id: 1044,
    vehicle: '04',
    title: 'Монтаж перекрытий',
    location: 'ЖК «Южный»',
    start: 13,
    end: 18,
    tone: 'reserved',
  },
  {
    id: 1045,
    vehicle: '07',
    title: 'Вывоз грунта',
    location: 'ЖК «Горизонт»',
    start: 8,
    end: 16,
    tone: 'lime',
  },
  {
    id: 1046,
    vehicle: '08',
    title: 'Траншея водопровода',
    location: 'Промышленный парк',
    start: 9,
    end: 17,
    tone: 'blue',
  },
  {
    id: 1047,
    vehicle: '09',
    title: 'Профилирование дороги',
    location: 'Объездная дорога, участок 4',
    start: 8,
    end: 18,
    tone: 'lime',
  },
];

export const INITIAL_REQUESTS: Request[] = [
  {
    id: 1048,
    title: 'Планировка участка',
    location: 'ЖК «Северный», корпус 2',
    category: 'Экскаватор-погрузчик',
    start: 13,
    end: 17,
    urgent: true,
    branchId: 'b1',
    creatorId: 'u-dept',
  },
  {
    id: 1049,
    title: 'Погрузка щебня',
    location: 'База «Стройресурс»',
    category: 'Погрузчик',
    start: 12,
    end: 15,
    urgent: false,
    branchId: 'b1',
    creatorId: 'u-mechanic',
  },
  {
    id: 1050,
    title: 'Благоустройство',
    location: 'Сквер на Молодёжной',
    category: 'Мини-погрузчик',
    start: 14,
    end: 18,
    urgent: false,
    branchId: 'b1',
    creatorId: 'u-master',
  },
];

export const INITIAL_WAYBILLS: Waybill[] = [
  {
    id: 'w-01',
    vehicleId: '01',
    driverId: 'd01',
    driverName: 'Алексей Соколов',
    licenseCategory: 'C, E',
    weekStart: '2026-09-08',
    odometerStart: 124580,
  },
  {
    id: 'w-03',
    vehicleId: '03',
    driverId: 'd03',
    driverName: 'Игорь Волков',
    licenseCategory: 'C, E',
    weekStart: '2026-09-08',
    odometerStart: 98240,
  },
  {
    id: 'w-07',
    vehicleId: '07',
    driverId: 'd07',
    driverName: 'Андрей Петров',
    licenseCategory: 'C, E',
    weekStart: '2026-09-08',
    odometerStart: 156110,
  },
];

export const INITIAL_TIMESHEET: TimesheetEntry[] = [
  {
    id: 't-1',
    driverId: 'd01',
    month: '2026-09',
    requestId: 1041,
    hours: 2,
    type: 'overtime',
    note: 'ЖК «Горизонт» · сверх смены',
  },
  {
    id: 't-2',
    driverId: 'd03',
    month: '2026-09',
    hours: 8,
    type: 'weekend',
    note: 'Суббота · доставка щебня',
  },
];

export const INITIAL_FUELINGS: Fueling[] = [
  {
    id: 'f-1',
    vehicleId: '01',
    fueledAt: '2026-09-10',
    liters: 80,
    source: 'cheque',
    amount: 4800,
  },
  {
    id: 'f-2',
    vehicleId: '03',
    fueledAt: '2026-09-11',
    liters: 120,
    source: 'program',
    amount: 7200,
  },
  {
    id: 'f-3',
    vehicleId: '07',
    fueledAt: '2026-09-11',
    liters: 95,
    source: 'program',
    amount: 5700,
  },
];

export const INITIAL_EVENTS: GarageEvent[] = [
  {
    time: '10:42',
    title: 'КАМАЗ 65115 прибыл на объект',
    detail: 'Игорь Волков · доставка щебня',
    type: 'arrival',
  },
  {
    time: '10:30',
    title: 'Новая срочная заявка № 1048',
    detail: 'ЖК «Северный» · требуется назначение',
    type: 'request',
  },
  {
    time: '10:15',
    title: 'Bobcat S530 готов к выезду',
    detail: 'Предсменный осмотр завершён',
    type: 'ready',
  },
];

export const DISPATCHERS: Dispatcher[] = [
  {
    name: 'Анна Миронова',
    initials: 'АМ',
    role: 'Старший диспетчер',
    time: '08:00–20:00',
    color: 'violet',
  },
  {
    name: 'Марк Дроздов',
    initials: 'МД',
    role: 'Диспетчер',
    time: '08:00–20:00',
    color: 'peach',
  },
  {
    name: 'Елена Новикова',
    initials: 'ЕН',
    role: 'Диспетчер',
    time: '10:00–22:00',
    color: 'mint',
  },
];
